import { SpaceshipState } from '../../types/index';

export function createSpaceship(): SpaceshipState {
  return {
    id: 'spaceship',
    x: 1000,
    y: 4000,
    angle: 0,
    vx: 0,
    vy: 0,
    angularVelocity: 0,
    health: 500,
    maxHealth: 500,
    shields: 300,
    maxShields: 300,
    shieldRegenRate: 5,
    ore: 0,
    thrusterPower: 0.34,
    weaponPower: 0.33,
    shieldPower: 0.33,
    turretAngle: 0,
    miningLaserActive: false,
    miningLaserTarget: null,
    components: {
      thrusters: { health: 100, maxHealth: 100, broken: false },
      weapons:   { health: 100, maxHealth: 100, broken: false },
      shields:   { health: 100, maxHealth: 100, broken: false },
      recon:     { health: 100, maxHealth: 100, broken: false },
    },
    upgrades: {
      weapons: 0,
      thrusters: 0,
      shields: 0,
      recon: 0,
      hasStrafing: false,
      hasMountedGuns: false,
      hasMissiles: false,
      hasHeatSeekingMissiles: false,
      hasBunkerBusters: false,
      hasActiveScan: false,
      hasScoutDrone: false,
      hasCollisionShield: false,
      hasShieldSponge: false,
    },
    mainGunCooldown: 0,
    missileCooldown: 0,
    missiles: 0,
    maxMissiles: 6,
    activeScanCooldown: 0,
    shieldRegenPaused: false,
  };
}
